#include "CodeGenerator.h"

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4244)
#endif
#include <llvm/MC/TargetRegistry.h>
#include <llvm/Support/TargetSelect.h>
#include <llvm/Target/TargetOptions.h>
#include <llvm/IR/LegacyPassManager.h>
#include <llvm/Support/FileSystem.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/TargetParser/Host.h>
#include <llvm/Passes/PassBuilder.h>
#include <llvm/Transforms/IPO/ModuleInliner.h>
#include <llvm/Transforms/IPO/GlobalDCE.h>
#include <llvm/Transforms/IPO/DeadArgumentElimination.h>
#include <llvm/Transforms/IPO/CalledValuePropagation.h>
#include <llvm/Transforms/Scalar/SROA.h>
#include <llvm/Transforms/Scalar/GVN.h>
#include <llvm/Transforms/Scalar/EarlyCSE.h>
#include <llvm/Transforms/Scalar/ConstraintElimination.h>
#include <llvm/Transforms/InstCombine/InstCombine.h>
#include <llvm/Bitcode/BitcodeWriter.h>
#include <llvm/IR/Verifier.h>
#include <llvm/IR/Attributes.h>
#include <llvm/Transforms/Scalar/RewriteStatepointsForGC.h>
#include <llvm/IR/InstIterator.h>
#include <llvm/IR/InstrTypes.h>
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#include <fmt/core.h>
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>

namespace ts {

/// Fix gc.relocate indices generated by LLVM 18.1 RS4GC.
/// RS4GC counts the statepoint result value as gc-live[0], making explicit
/// gc-live bundle entries start at index 1. The LLVM verifier and backend
/// expect 0-based indexing into the gc-live bundle entries only.
/// This pass subtracts 1 from out-of-bounds indices to correct the mismatch.
static void fixupGCRelocateIndices(llvm::Module& M) {
    unsigned fixed = 0;
    for (auto& F : M) {
        if (!F.hasGC()) continue;

        for (auto& I : llvm::instructions(F)) {
            auto* CI = llvm::dyn_cast<llvm::CallInst>(&I);
            if (!CI) continue;

            auto* callee = CI->getCalledFunction();
            if (!callee || !callee->getName().starts_with("llvm.experimental.gc.relocate"))
                continue;

            // Get the statepoint (first operand of gc.relocate is the token)
            auto* statepoint = llvm::dyn_cast<llvm::CallBase>(CI->getArgOperand(0));
            if (!statepoint) continue;

            // Get gc-live bundle to determine valid index range
            auto gcLiveBundle = statepoint->getOperandBundle("gc-live");
            if (!gcLiveBundle) continue;

            unsigned gcLiveCount = gcLiveBundle->Inputs.size();
            if (gcLiveCount == 0) continue;

            auto* baseIdxConst = llvm::dyn_cast<llvm::ConstantInt>(CI->getArgOperand(1));
            auto* derivedIdxConst = llvm::dyn_cast<llvm::ConstantInt>(CI->getArgOperand(2));
            if (!baseIdxConst || !derivedIdxConst) continue;

            unsigned baseIdx = baseIdxConst->getZExtValue();
            unsigned derivedIdx = derivedIdxConst->getZExtValue();

            bool needsFix = false;
            unsigned newBaseIdx = baseIdx;
            unsigned newDerivedIdx = derivedIdx;

            if (baseIdx >= gcLiveCount) {
                newBaseIdx = baseIdx - 1;
                needsFix = true;
            }
            if (derivedIdx >= gcLiveCount) {
                newDerivedIdx = derivedIdx - 1;
                needsFix = true;
            }

            if (needsFix) {
                auto* intTy = baseIdxConst->getType();
                CI->setArgOperand(1, llvm::ConstantInt::get(intTy, newBaseIdx));
                CI->setArgOperand(2, llvm::ConstantInt::get(intTy, newDerivedIdx));
                fixed++;
            }
        }
    }
    if (fixed > 0) {
        SPDLOG_INFO("Fixed {} gc.relocate indices (RS4GC off-by-one in LLVM 18)", fixed);
    }
}

/// Add empty "deopt"() operand bundles to all calls/invokes in gc-attributed
/// functions that don't already have one. RS4GC requires deopt bundles to
/// generate correct operand-bundle-based statepoints with valid gc.relocate indices.
static void addDeoptBundles(llvm::Module& M) {
    unsigned modified = 0;
    for (auto& F : M) {
        if (!F.hasGC()) continue;

        // Collect calls that need deopt bundles (can't modify while iterating)
        llvm::SmallVector<llvm::CallBase*, 32> callsToModify;
        for (auto& I : llvm::instructions(F)) {
            auto* CB = llvm::dyn_cast<llvm::CallBase>(&I);
            if (!CB) continue;

            // Skip if already has a deopt bundle
            if (CB->getOperandBundle(llvm::LLVMContext::OB_deopt)) continue;

            // Skip intrinsics (they don't need deopt bundles)
            if (auto* callee = CB->getCalledFunction()) {
                if (callee->isIntrinsic()) continue;
            }

            callsToModify.push_back(CB);
        }

        for (auto* CB : callsToModify) {
            // Create a new call with all existing operand bundles plus an empty deopt bundle
            llvm::SmallVector<llvm::OperandBundleDef, 2> newBundles;
            CB->getOperandBundlesAsDefs(newBundles);
            newBundles.emplace_back("deopt", llvm::ArrayRef<llvm::Value*>());

            llvm::CallBase* newCB;
            if (auto* invoke = llvm::dyn_cast<llvm::InvokeInst>(CB)) {
                newCB = llvm::InvokeInst::Create(invoke, newBundles, CB);
            } else {
                newCB = llvm::CallInst::Create(llvm::cast<llvm::CallInst>(CB), newBundles, CB);
            }
            newCB->takeName(CB);
            CB->replaceAllUsesWith(newCB);
            CB->eraseFromParent();
            modified++;
        }
    }
    if (modified > 0) {
        SPDLOG_INFO("Added deopt bundles to {} calls for RS4GC", modified);
    }
}

CodeGenerator::CodeGenerator(llvm::Module* module) : module(module) {}

bool CodeGenerator::setupTargetMachine(const std::string& optLevel) {
    auto targetTriple = llvm::sys::getDefaultTargetTriple();
    module->setTargetTriple(targetTriple);

    std::string error;
    auto target = llvm::TargetRegistry::lookupTarget(targetTriple, error);

    if (!target) {
        SPDLOG_ERROR("Could not find target for triple {}: {}", targetTriple, error);
        return false;
    }

    auto cpu = "generic";
    auto features = "";

    llvm::TargetOptions opt;
    auto rm = llvm::Reloc::Model::PIC_;
    
    llvm::CodeGenOptLevel optLvl = llvm::CodeGenOptLevel::None;
    if (optLevel == "1") optLvl = llvm::CodeGenOptLevel::Less;
    else if (optLevel == "2") optLvl = llvm::CodeGenOptLevel::Default;
    else if (optLevel == "3") optLvl = llvm::CodeGenOptLevel::Aggressive;

    targetMachine = std::unique_ptr<llvm::TargetMachine>(
        target->createTargetMachine(targetTriple, cpu, features, opt, rm, std::nullopt, optLvl));

    if (!targetMachine) {
        SPDLOG_ERROR("Could not create target machine");
        return false;
    }

    // Disable FastISel when GC statepoints are enabled.
    // FastISel (used at -O0) doesn't support gc.statepoint lowering;
    // SelectionDAG must be used to properly lower statepoints to calls + stack maps.
    if (enableGCStatepoints_) {
        targetMachine->setFastISel(false);
        targetMachine->setO0WantsFastISel(false);
    }

    module->setDataLayout(targetMachine->createDataLayout());
    return true;
}

// Annotate runtime function declarations with semantic attributes.
// This enables LLVM passes (GVN, EarlyCSE, LICM, InstCombine) to optimize
// around runtime calls by understanding their side-effect profiles.
static void annotateRuntimeFunctions(llvm::Module& M) {
    auto annotate = [&](const char* name, bool readnone, bool readonly,
                        bool nounwind, bool willreturn, bool noreturn = false) {
        if (auto* F = M.getFunction(name)) {
            if (nounwind) F->addFnAttr(llvm::Attribute::NoUnwind);
            if (willreturn) F->addFnAttr(llvm::Attribute::WillReturn);
            if (noreturn) F->addFnAttr(llvm::Attribute::NoReturn);
            if (readnone) F->setDoesNotAccessMemory();
            else if (readonly) F->setOnlyReadsMemory();
        }
    };

    // --- Pure functions (readnone): NaN-boxing arithmetic only, no memory access ---
    annotate("ts_value_make_int",       true,  false, true, true);
    annotate("ts_value_make_double",    true,  false, true, true);
    annotate("ts_value_make_bool",      true,  false, true, true);
    // make_string/make_object are effectively identity (pointer IS encoding)
    annotate("ts_value_make_string",    true,  false, true, true);
    annotate("ts_value_make_object",    true,  false, true, true);
    annotate("ts_value_make_array",     true,  false, true, true);
    annotate("ts_value_make_promise",   true,  false, true, true);
    annotate("ts_value_make_function_object", true, false, true, true);
    annotate("ts_value_make_bigint",    true,  false, true, true);
    annotate("ts_value_make_symbol",    true,  false, true, true);
    annotate("ts_value_make_undefined", true,  false, true, true);
    annotate("ts_value_make_null",      true,  false, true, true);
    annotate("ts_ensure_boxed",         true,  false, true, true);
    // Decoding: pure tag extraction / arithmetic
    annotate("ts_value_get_int",        true,  false, true, true);
    annotate("ts_value_get_object",     true,  false, true, true);
    // Tag checks: pure integer comparisons
    annotate("ts_value_is_null",        true,  false, true, true);
    annotate("ts_value_is_undefined",   true,  false, true, true);
    annotate("ts_value_is_nullish",     true,  false, true, true);
    annotate("ts_value_strict_eq_bool", true,  false, true, true);
    annotate("ts_nanbox_safe_unbox",    true,  false, true, true);

    // --- Read-only functions: read object metadata, no side effects ---
    // These may dereference pointers (string magic, string length) but don't mutate
    annotate("ts_value_get_double",     false, true,  true, true);
    annotate("ts_value_get_bool",       false, true,  true, true);
    annotate("ts_value_get_string",     false, true,  true, true);
    annotate("ts_value_to_bool",        false, true,  true, true);
    annotate("ts_string_length",        false, true,  true, true);
    annotate("ts_array_length",         false, true,  true, true);
    annotate("ts_typeof",              false, true,  true, true);
    annotate("ts_instanceof",          false, true,  true, true);
    annotate("ts_value_box_any",        false, true,  true, true);

    // --- Side-effecting but nounwind + willreturn ---
    // These read/write heap objects but don't throw C++ exceptions (longjmp for JS)
    annotate("ts_object_get_property",  false, false, true, true);
    annotate("ts_object_get_dynamic",   false, false, true, true);
    annotate("ts_object_set_property",  false, false, true, true);
    annotate("ts_object_set_dynamic",   false, false, true, true);
    annotate("ts_array_push",           false, false, true, true);
    annotate("ts_array_get",            false, false, true, true);
    annotate("ts_array_set",            false, false, true, true);
    annotate("ts_array_get_as_value",   false, false, true, true);
    annotate("ts_map_create",           false, false, true, true);
    annotate("ts_string_concat",        false, false, true, true);
    annotate("ts_string_from_value",    false, false, true, true);
    annotate("ts_alloc",                false, false, true, true);

    // --- Control flow: noreturn ---
    annotate("ts_throw",                false, false, true, false, /*noreturn=*/true);

    // NEVER annotate: ts_gc_write_barrier, ts_gc_safepoint, ts_gc_mark_object
}

void CodeGenerator::runOptimizations(const std::string& optLevel) {
    // Step 0: Annotate runtime function declarations with semantic attributes
    annotateRuntimeFunctions(*module);

    llvm::LoopAnalysisManager LAM;
    llvm::FunctionAnalysisManager FAM;
    llvm::CGSCCAnalysisManager CGAM;
    llvm::ModuleAnalysisManager MAM;

    llvm::PassBuilder PB(targetMachine.get());

    // Extension point: propagate known function pointers through closure dispatch
    PB.registerPipelineStartEPCallback(
        [](llvm::ModulePassManager& MPM, llvm::OptimizationLevel Level) {
            if (Level == llvm::OptimizationLevel::O0) return;
            MPM.addPass(llvm::CalledValuePropagationPass());
        });

    // Extension point: after each inlining round, catch box/unbox patterns
    PB.registerPeepholeEPCallback(
        [](llvm::FunctionPassManager& FPM, llvm::OptimizationLevel Level) {
            if (Level == llvm::OptimizationLevel::O0) return;
            FPM.addPass(llvm::InstCombinePass());
            FPM.addPass(llvm::EarlyCSEPass(/*UseMemorySSA=*/true));
        });

    // Extension point: eliminate redundant type guards before vectorizer
    PB.registerVectorizerStartEPCallback(
        [](llvm::FunctionPassManager& FPM, llvm::OptimizationLevel Level) {
            if (Level == llvm::OptimizationLevel::O0) return;
            FPM.addPass(llvm::ConstraintEliminationPass());
        });

    PB.registerModuleAnalyses(MAM);
    PB.registerCGSCCAnalyses(CGAM);
    PB.registerFunctionAnalyses(FAM);
    PB.registerLoopAnalyses(LAM);
    PB.crossRegisterProxies(LAM, FAM, CGAM, MAM);

    llvm::OptimizationLevel level;
    if (optLevel == "0") level = llvm::OptimizationLevel::O0;
    else if (optLevel == "1") level = llvm::OptimizationLevel::O1;
    else if (optLevel == "2") level = llvm::OptimizationLevel::O2;
    else if (optLevel == "3") level = llvm::OptimizationLevel::O3;
    else if (optLevel == "s") level = llvm::OptimizationLevel::Os;
    else if (optLevel == "z") level = llvm::OptimizationLevel::Oz;
    else level = llvm::OptimizationLevel::O0;

    if (level != llvm::OptimizationLevel::O0) {
        SPDLOG_INFO("Running IR optimizations (Level O{})", optLevel);

        // Use buildPerModuleDefaultPipeline as the core. It includes:
        // SROA, EarlyCSE, InstCombine, SimplifyCFG, GVN, LICM,
        // LoopUnroll, CGSCC Inliner, GlobalOpt, IPSCCP, etc.
        // Our extension point callbacks inject ts-aot-specific passes.
        llvm::ModulePassManager MPM =
            PB.buildPerModuleDefaultPipeline(level);

        // Post-pipeline cleanup
        MPM.addPass(llvm::DeadArgumentEliminationPass());
        MPM.addPass(llvm::GlobalDCEPass());

        MPM.run(*module, MAM);
    }

    // Run RewriteStatepointsForGC pass when GC statepoints are enabled.
    // This must run AFTER standard optimizations but BEFORE code emission.
    // RS4GC rewrites calls with "deopt" bundles into gc.statepoint + gc.relocate
    // and generates the .llvm_stackmaps section for precise stack scanning.
    if (enableGCStatepoints_) {
        // Add empty "deopt"() bundles to all calls in gc-attributed functions.
        // RS4GC requires these to generate operand-bundle-based statepoints
        // with correct gc.relocate indices.
        addDeoptBundles(*module);

        SPDLOG_INFO("Running RewriteStatepointsForGC pass");
        llvm::ModulePassManager GCMPM;
        GCMPM.addPass(llvm::RewriteStatepointsForGC());
        GCMPM.run(*module, MAM);

        // Fix gc.relocate indices: LLVM 18.1 RS4GC generates off-by-one indices
        // (counts statepoint result as gc-live[0]). Fix them to 0-based gc-live
        // bundle indexing that the verifier and backend expect.
        fixupGCRelocateIndices(*module);

        // Verify the module after RS4GC + fixup
        std::string errorStr;
        llvm::raw_string_ostream os(errorStr);
        if (llvm::verifyModule(*module, &os)) {
            SPDLOG_WARN("Module verification after RS4GC: {}", errorStr);
        } else {
            SPDLOG_INFO("Module verification passed after RS4GC");
        }
    }
}

bool CodeGenerator::emitObjectFile(const std::string& filename, const std::string& optLevel) {
    std::string errorStr;
    llvm::raw_string_ostream os(errorStr);
    if (llvm::verifyModule(*module, &os)) {
        SPDLOG_ERROR("LLVM Module verification failed: {}", errorStr);
        return false;
    }

    if (!setupTargetMachine(optLevel)) {
        return false;
    }

    runOptimizations(optLevel);

    std::error_code ec;
    llvm::raw_fd_ostream dest(filename, ec, llvm::sys::fs::OF_None);

    if (ec) {
        SPDLOG_ERROR("Could not open file {}: {}", filename, ec.message());
        return false;
    }

    llvm::legacy::PassManager pass;
    auto fileType = llvm::CodeGenFileType::ObjectFile;

    if (targetMachine->addPassesToEmitFile(pass, dest, nullptr, fileType)) {
        SPDLOG_ERROR("TargetMachine can't emit a file of this type");
        return false;
    }

    SPDLOG_INFO("Dumping debug IR to debug_ir.ll");
    std::error_code ec2;
    llvm::raw_fd_ostream debugFile("debug_ir.ll", ec2, llvm::sys::fs::OF_None);
    module->print(debugFile, nullptr);
    debugFile.flush();

    SPDLOG_INFO("Starting CodeGen passes");
    pass.run(*module);
    SPDLOG_INFO("Finished CodeGen passes");
    dest.flush();

    return true;
}

bool CodeGenerator::emitBitcode(const std::string& filename) {
    std::error_code ec;
    llvm::raw_fd_ostream dest(filename, ec, llvm::sys::fs::OF_None);
    if (ec) {
        SPDLOG_ERROR("Could not open file {}: {}", filename, ec.message());
        return false;
    }
    llvm::WriteBitcodeToFile(*module, dest);
    return true;
}

bool CodeGenerator::emitAssembly(const std::string& filename) {
    std::error_code ec;
    llvm::raw_fd_ostream dest(filename, ec, llvm::sys::fs::OF_None);
    if (ec) {
        SPDLOG_ERROR("Could not open file {}: {}", filename, ec.message());
        return false;
    }
    module->print(dest, nullptr);
    return true;
}

} // namespace ts
