#include "CodeGenerator.h"
#include <cstdlib>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4244)
#endif
#include <llvm/MC/TargetRegistry.h>
#include <llvm/Support/TargetSelect.h>
#include <llvm/Target/TargetOptions.h>
#include <llvm/IR/LegacyPassManager.h>
#include <llvm/Support/FileSystem.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/TargetParser/Host.h>
#include <llvm/Passes/PassBuilder.h>
#include <llvm/Transforms/IPO/ModuleInliner.h>
#include <llvm/Transforms/IPO/GlobalDCE.h>
#include <llvm/Transforms/IPO/DeadArgumentElimination.h>
#include <llvm/Transforms/IPO/CalledValuePropagation.h>
#include <llvm/Transforms/Scalar/SROA.h>
#include <llvm/Transforms/Scalar/GVN.h>
#include <llvm/Transforms/Scalar/EarlyCSE.h>
#include <llvm/Transforms/Scalar/ConstraintElimination.h>
#include <llvm/Transforms/InstCombine/InstCombine.h>
#include <llvm/Bitcode/BitcodeWriter.h>
#include <llvm/IR/Verifier.h>
#include <llvm/IR/Attributes.h>
#include <llvm/Transforms/Scalar/RewriteStatepointsForGC.h>
#include <llvm/Transforms/Instrumentation/InstrProfiling.h>
#include <llvm/IR/InstIterator.h>
#include <llvm/IR/InstrTypes.h>
#include <llvm/IR/IRBuilder.h>
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#include <fmt/core.h>
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>

namespace ts {

/// Fix gc.relocate indices generated by LLVM 18.1 RS4GC.
/// RS4GC counts the statepoint result value as gc-live[0], making explicit
/// gc-live bundle entries start at index 1. The LLVM verifier and backend
/// expect 0-based indexing into the gc-live bundle entries only.
/// This pass subtracts 1 from out-of-bounds indices to correct the mismatch.
static void fixupGCRelocateIndices(llvm::Module& M) {
    unsigned fixed = 0;
    for (auto& F : M) {
        if (!F.hasGC()) continue;

        for (auto& I : llvm::instructions(F)) {
            auto* CI = llvm::dyn_cast<llvm::CallInst>(&I);
            if (!CI) continue;

            auto* callee = CI->getCalledFunction();
            if (!callee || !callee->getName().starts_with("llvm.experimental.gc.relocate"))
                continue;

            // Get the statepoint (first operand of gc.relocate is the token)
            auto* statepoint = llvm::dyn_cast<llvm::CallBase>(CI->getArgOperand(0));
            if (!statepoint) continue;

            // Get gc-live bundle to determine valid index range
            auto gcLiveBundle = statepoint->getOperandBundle("gc-live");
            if (!gcLiveBundle) continue;

            unsigned gcLiveCount = gcLiveBundle->Inputs.size();
            if (gcLiveCount == 0) continue;

            auto* baseIdxConst = llvm::dyn_cast<llvm::ConstantInt>(CI->getArgOperand(1));
            auto* derivedIdxConst = llvm::dyn_cast<llvm::ConstantInt>(CI->getArgOperand(2));
            if (!baseIdxConst || !derivedIdxConst) continue;

            unsigned baseIdx = baseIdxConst->getZExtValue();
            unsigned derivedIdx = derivedIdxConst->getZExtValue();

            bool needsFix = false;
            unsigned newBaseIdx = baseIdx;
            unsigned newDerivedIdx = derivedIdx;

            if (baseIdx >= gcLiveCount) {
                newBaseIdx = baseIdx - 1;
                needsFix = true;
            }
            if (derivedIdx >= gcLiveCount) {
                newDerivedIdx = derivedIdx - 1;
                needsFix = true;
            }

            if (needsFix) {
                auto* intTy = baseIdxConst->getType();
                CI->setArgOperand(1, llvm::ConstantInt::get(intTy, newBaseIdx));
                CI->setArgOperand(2, llvm::ConstantInt::get(intTy, newDerivedIdx));
                fixed++;
            }
        }
    }
    if (fixed > 0) {
        SPDLOG_INFO("Fixed {} gc.relocate indices (RS4GC off-by-one in LLVM 18)", fixed);
    }
}

/// Add empty "deopt"() operand bundles to all calls/invokes in gc-attributed
/// functions that don't already have one. RS4GC requires deopt bundles to
/// generate correct operand-bundle-based statepoints with valid gc.relocate indices.
static void addDeoptBundles(llvm::Module& M) {
    unsigned modified = 0;
    for (auto& F : M) {
        if (!F.hasGC()) continue;

        // Collect calls that need deopt bundles (can't modify while iterating)
        llvm::SmallVector<llvm::CallBase*, 32> callsToModify;
        for (auto& I : llvm::instructions(F)) {
            auto* CB = llvm::dyn_cast<llvm::CallBase>(&I);
            if (!CB) continue;

            // Skip if already has a deopt bundle
            if (CB->getOperandBundle(llvm::LLVMContext::OB_deopt)) continue;

            // Skip intrinsics (they don't need deopt bundles)
            if (auto* callee = CB->getCalledFunction()) {
                if (callee->isIntrinsic()) continue;
            }

            callsToModify.push_back(CB);
        }

        for (auto* CB : callsToModify) {
            // Create a new call with all existing operand bundles plus an empty deopt bundle
            llvm::SmallVector<llvm::OperandBundleDef, 2> newBundles;
            CB->getOperandBundlesAsDefs(newBundles);
            newBundles.emplace_back("deopt", llvm::ArrayRef<llvm::Value*>());

            llvm::CallBase* newCB;
            if (auto* invoke = llvm::dyn_cast<llvm::InvokeInst>(CB)) {
                newCB = llvm::InvokeInst::Create(invoke, newBundles, CB);
            } else {
                newCB = llvm::CallInst::Create(llvm::cast<llvm::CallInst>(CB), newBundles, CB);
            }
            newCB->takeName(CB);
            CB->replaceAllUsesWith(newCB);
            CB->eraseFromParent();
            modified++;
        }
    }
    if (modified > 0) {
        SPDLOG_INFO("Added deopt bundles to {} calls for RS4GC", modified);
    }
}

/// GC-001 Phase 3b step 2: normalize the runtime-call boundary to addrspace(0).
///
/// Step 1 made ALL pointers addrspace(1) under --gc-statepoints, including the
/// signatures of external runtime functions (the C ABI), which (a) mismatches
/// addrspace(0) string-literal globals passed to `const char*` params and
/// (b) is the wrong model (per the GC-001 decision: GC VALUES are addrspace(1),
/// the C boundary is addrspace(0)). This pass rewrites every external DECLARATION
/// (no body; not an intrinsic) so its pointer params/return are addrspace(0), and
/// inserts addrspacecasts at each call site: args (1)->(0) before the call, the
/// pointer result (0)->(1) after. The original addrspace(1) arg values are left
/// untouched (only throwaway casts are added), so they remain live across the
/// call and RS4GC still relocates them. User functions (with bodies) keep their
/// addrspace(1) signatures — user->user calls stay addrspace(1) and are rooted.
static void normalizeRuntimeBoundaryAddrSpaces(llvm::Module& M) {
    llvm::LLVMContext& ctx = M.getContext();
    llvm::Type* p0 = llvm::PointerType::get(ctx, 0);
    auto toP0 = [&](llvm::Type* t) -> llvm::Type* {
        auto* pt = llvm::dyn_cast<llvm::PointerType>(t);
        return (pt && pt->getAddressSpace() != 0) ? p0 : t;
    };

    // Collect candidate external declarations first (we mutate the module).
    llvm::SmallVector<llvm::Function*, 64> candidates;
    for (auto& F : M) {
        if (!F.isDeclaration() || F.isIntrinsic()) continue;
        if (F.getName().starts_with("llvm.")) continue;
        // Only rewrite if some pointer param/return is in a non-zero addrspace.
        llvm::FunctionType* ft = F.getFunctionType();
        bool needs = toP0(ft->getReturnType()) != ft->getReturnType();
        for (llvm::Type* pty : ft->params()) needs |= (toP0(pty) != pty);
        if (!needs) continue;
        // Only rewrite if every use is a direct call to F (no function-pointer uses).
        bool onlyCalls = true;
        for (llvm::User* U : F.users()) {
            auto* CB = llvm::dyn_cast<llvm::CallBase>(U);
            if (!CB || CB->getCalledOperand() != &F) { onlyCalls = false; break; }
        }
        if (!onlyCalls) continue;
        candidates.push_back(&F);
    }

    unsigned rewritten = 0, callsFixed = 0;
    for (llvm::Function* F : candidates) {
        llvm::FunctionType* oldFT = F->getFunctionType();
        llvm::SmallVector<llvm::Type*, 8> newParams;
        for (llvm::Type* pty : oldFT->params()) newParams.push_back(toP0(pty));
        llvm::Type* newRet = toP0(oldFT->getReturnType());
        llvm::FunctionType* newFT =
            llvm::FunctionType::get(newRet, newParams, oldFT->isVarArg());

        std::string name = F->getName().str();
        F->setName(name + ".as1sig");
        llvm::Function* newF = llvm::Function::Create(
            newFT, F->getLinkage(), name, &M);
        newF->setAttributes(F->getAttributes());
        newF->setCallingConv(F->getCallingConv());

        // Rewrite every call site.
        llvm::SmallVector<llvm::CallBase*, 16> calls;
        for (llvm::User* U : F->users())
            if (auto* CB = llvm::dyn_cast<llvm::CallBase>(U)) calls.push_back(CB);
        for (llvm::CallBase* CB : calls) {
            llvm::IRBuilder<> b(CB);
            llvm::SmallVector<llvm::Value*, 8> newArgs;
            for (unsigned i = 0; i < CB->arg_size(); ++i) {
                llvm::Value* a = CB->getArgOperand(i);
                auto* apt = llvm::dyn_cast<llvm::PointerType>(a->getType());
                if (apt && apt->getAddressSpace() != 0)
                    a = b.CreateAddrSpaceCast(a, p0, "gc.arg.raw");
                newArgs.push_back(a);
            }
            llvm::SmallVector<llvm::OperandBundleDef, 2> bundles;
            CB->getOperandBundlesAsDefs(bundles);
            llvm::CallInst* newCall = b.CreateCall(newFT, newF, newArgs, bundles);
            newCall->setCallingConv(CB->getCallingConv());
            // Reconcile result type: new call returns addrspace(0); old uses may
            // expect addrspace(1).
            llvm::Value* repl = newCall;
            if (CB->getType() != newCall->getType()) {
                if (CB->getType()->isPointerTy() && newCall->getType()->isPointerTy())
                    repl = b.CreateAddrSpaceCast(newCall, CB->getType(), "gc.ret.gc");
            }
            if (!CB->use_empty()) CB->replaceAllUsesWith(repl);
            CB->eraseFromParent();
            callsFixed++;
        }
        F->eraseFromParent();
        rewritten++;
    }

    // Phase 2: reconcile EVERY call to an external declaration (including those
    // that were already addrspace(0) — e.g. ts_console_log_value declared via a
    // handler with raw getPtrTy). For each pointer arg whose addrspace differs
    // from the callee's declared param addrspace, insert an addrspacecast right
    // before the call. Idempotent: calls already fixed in Phase 1 pass through
    // unchanged. The original addrspace(1) values stay live for RS4GC.
    unsigned phase2 = 0;
    for (auto& F : M) {
        for (auto& I : llvm::instructions(F)) {
            auto* CB = llvm::dyn_cast<llvm::CallBase>(&I);
            if (!CB) continue;
            llvm::Function* callee = CB->getCalledFunction();
            if (!callee || !callee->isDeclaration() || callee->isIntrinsic()) continue;
            if (callee->getName().starts_with("llvm.")) continue;
            llvm::FunctionType* ft = callee->getFunctionType();
            llvm::IRBuilder<> b(CB);
            unsigned nfixed = ft->getNumParams();
            for (unsigned i = 0; i < CB->arg_size(); ++i) {
                llvm::Value* a = CB->getArgOperand(i);
                auto* apt = llvm::dyn_cast<llvm::PointerType>(a->getType());
                if (!apt) continue;
                // Determine the expected addrspace: declared param for fixed args,
                // else addrspace(0) for varargs (C ABI).
                unsigned want = (i < nfixed)
                    ? (llvm::isa<llvm::PointerType>(ft->getParamType(i))
                         ? llvm::cast<llvm::PointerType>(ft->getParamType(i))->getAddressSpace()
                         : apt->getAddressSpace())
                    : 0u;
                if (apt->getAddressSpace() != want) {
                    llvm::Value* c = b.CreateAddrSpaceCast(
                        a, llvm::PointerType::get(ctx, want), "gc.arg.cast");
                    CB->setArgOperand(i, c);
                    phase2++;
                }
            }
        }
    }

    if (rewritten > 0 || phase2 > 0) {
        SPDLOG_INFO("GC boundary: normalized {} runtime decls to addrspace(0), "
                    "fixed {} call sites (phase1) + {} arg casts (phase2)",
                    rewritten, callsFixed, phase2);
    }
}

/// GC-001 Phase 3b: canonicalize call argument integer widths to the callee's
/// declared signature.
///
/// HIRToLLVM emits some runtime boxing calls (notably ts_value_make_bool, whose
/// C param is `bool`) with inconsistent integer widths across sites — i1 at some,
/// i32/i64 at others. Opaque pointers let a call's FunctionType differ from the
/// callee declaration in the default build, so the verifier tolerates it. But
/// RS4GC re-derives the callee signature from the declaration and the verifier
/// then rejects every width-mismatched call ("Call parameter type does not match
/// function signature"). This pass rebuilds each direct call whose integer arg
/// widths differ from the callee's declared params, inserting zext/trunc so the
/// whole module agrees. Pointer/addrspace differences are left to
/// normalizeRuntimeBoundaryAddrSpaces; only integer-width mismatches are touched.
/// ABI-safe: x86-64 passes small integers in registers and the callee reads the
/// width it declares, so zext/trunc to the declared width preserves the value.
static void canonicalizeIntCallArgs(llvm::Module& M) {
    unsigned fixed = 0;
    for (auto& F : M) {
        llvm::SmallVector<llvm::CallInst*, 16> toFix;
        for (auto& I : llvm::instructions(F)) {
            auto* CI = llvm::dyn_cast<llvm::CallInst>(&I);
            if (!CI) continue;
            llvm::Function* callee = CI->getCalledFunction();
            if (!callee || callee->isIntrinsic()) continue;
            llvm::FunctionType* ft = callee->getFunctionType();
            if (ft->isVarArg() || ft->getNumParams() != CI->arg_size()) continue;
            // Only act when every differing param is an integer-width-only diff.
            bool needs = false, intWidthOnly = true;
            for (unsigned i = 0; i < ft->getNumParams(); ++i) {
                llvm::Type* want = ft->getParamType(i);
                llvm::Type* have = CI->getArgOperand(i)->getType();
                if (want == have) continue;
                if (want->isIntegerTy() && have->isIntegerTy()) needs = true;
                else { intWidthOnly = false; break; }
            }
            if (needs && intWidthOnly) toFix.push_back(CI);
        }
        for (auto* CI : toFix) {
            llvm::Function* callee = CI->getCalledFunction();
            llvm::FunctionType* ft = callee->getFunctionType();
            llvm::IRBuilder<> b(CI);
            llvm::SmallVector<llvm::Value*, 8> args;
            for (unsigned i = 0; i < ft->getNumParams(); ++i) {
                llvm::Value* a = CI->getArgOperand(i);
                llvm::Type* want = ft->getParamType(i);
                if (a->getType() != want && want->isIntegerTy() && a->getType()->isIntegerTy()) {
                    unsigned aw = a->getType()->getIntegerBitWidth();
                    unsigned ww = want->getIntegerBitWidth();
                    a = aw < ww ? b.CreateZExt(a, want, "argz")
                      : aw > ww ? b.CreateTrunc(a, want, "argt")
                                : a;
                }
                args.push_back(a);
            }
            llvm::SmallVector<llvm::OperandBundleDef, 2> bundles;
            CI->getOperandBundlesAsDefs(bundles);
            llvm::CallInst* nc = b.CreateCall(ft, callee, args, bundles);
            nc->setCallingConv(CI->getCallingConv());
            nc->setAttributes(CI->getAttributes());
            nc->takeName(CI);
            if (!CI->use_empty()) CI->replaceAllUsesWith(nc);
            CI->eraseFromParent();
            fixed++;
        }
    }
    if (fixed) SPDLOG_INFO("Canonicalized {} call arg widths to declared callee signature", fixed);
}

CodeGenerator::CodeGenerator(llvm::Module* module) : module(module) {}

bool CodeGenerator::setupTargetMachine(const std::string& optLevel) {
    auto targetTriple = llvm::sys::getDefaultTargetTriple();
    module->setTargetTriple(targetTriple);

    std::string error;
    auto target = llvm::TargetRegistry::lookupTarget(targetTriple, error);

    if (!target) {
        SPDLOG_ERROR("Could not find target for triple {}: {}", targetTriple, error);
        return false;
    }

    auto cpu = "generic";
    auto features = "";

    llvm::TargetOptions opt;
    auto rm = llvm::Reloc::Model::PIC_;
    
    llvm::CodeGenOptLevel optLvl = llvm::CodeGenOptLevel::None;
    if (optLevel == "1") optLvl = llvm::CodeGenOptLevel::Less;
    else if (optLevel == "2") optLvl = llvm::CodeGenOptLevel::Default;
    else if (optLevel == "3") optLvl = llvm::CodeGenOptLevel::Aggressive;

    targetMachine = std::unique_ptr<llvm::TargetMachine>(
        target->createTargetMachine(targetTriple, cpu, features, opt, rm, std::nullopt, optLvl));

    if (!targetMachine) {
        SPDLOG_ERROR("Could not create target machine");
        return false;
    }

    // Disable FastISel when GC statepoints are enabled.
    // FastISel (used at -O0) doesn't support gc.statepoint lowering;
    // SelectionDAG must be used to properly lower statepoints to calls + stack maps.
    if (enableGCStatepoints_) {
        targetMachine->setFastISel(false);
        targetMachine->setO0WantsFastISel(false);
    }

    module->setDataLayout(targetMachine->createDataLayout());
    return true;
}

// Annotate runtime function declarations with semantic attributes.
// This enables LLVM passes (GVN, EarlyCSE, LICM, InstCombine) to optimize
// around runtime calls by understanding their side-effect profiles.
static void annotateRuntimeFunctions(llvm::Module& M) {
    auto annotate = [&](const char* name, bool readnone, bool readonly,
                        bool nounwind, bool willreturn, bool noreturn = false) {
        if (auto* F = M.getFunction(name)) {
            if (nounwind) F->addFnAttr(llvm::Attribute::NoUnwind);
            if (willreturn) F->addFnAttr(llvm::Attribute::WillReturn);
            if (noreturn) F->addFnAttr(llvm::Attribute::NoReturn);
            if (readnone) F->setDoesNotAccessMemory();
            else if (readonly) F->setOnlyReadsMemory();
        }
    };

    // --- Pure functions (readnone): NaN-boxing arithmetic only, no memory access ---
    annotate("ts_value_make_int",       true,  false, true, true);
    annotate("ts_value_make_double",    true,  false, true, true);
    annotate("ts_value_make_bool",      true,  false, true, true);
    // make_string/make_object are effectively identity (pointer IS encoding)
    annotate("ts_value_make_string",    true,  false, true, true);
    annotate("ts_value_make_object",    true,  false, true, true);
    annotate("ts_value_make_array",     true,  false, true, true);
    annotate("ts_value_make_promise",   true,  false, true, true);
    annotate("ts_value_make_function_object", true, false, true, true);
    annotate("ts_value_make_bigint",    true,  false, true, true);
    annotate("ts_value_make_symbol",    true,  false, true, true);
    annotate("ts_value_make_undefined", true,  false, true, true);
    annotate("ts_value_make_null",      true,  false, true, true);
    annotate("ts_ensure_boxed",         true,  false, true, true);
    // Decoding: pure tag extraction / arithmetic
    annotate("ts_value_get_int",        true,  false, true, true);
    annotate("ts_value_get_object",     true,  false, true, true);
    // Tag checks: pure integer comparisons
    annotate("ts_value_is_null",        true,  false, true, true);
    annotate("ts_value_is_undefined",   true,  false, true, true);
    annotate("ts_value_is_nullish",     true,  false, true, true);
    annotate("ts_value_strict_eq_bool", true,  false, true, true);
    annotate("ts_nanbox_safe_unbox",    true,  false, true, true);

    // --- Read-only functions: read object metadata, no side effects ---
    // These may dereference pointers (string magic, string length) but don't mutate
    annotate("ts_value_get_double",     false, true,  true, true);
    annotate("ts_value_get_bool",       false, true,  true, true);
    annotate("ts_value_get_string",     false, true,  true, true);
    annotate("ts_value_to_bool",        false, true,  true, true);
    annotate("ts_string_length",        false, true,  true, true);
    annotate("ts_array_length",         false, true,  true, true);
    annotate("ts_typeof",              false, true,  true, true);
    annotate("ts_instanceof",          false, true,  true, true);
    annotate("ts_value_box_any",        false, true,  true, true);

    // --- Side-effecting, nounwind only (NO willreturn) ---
    // These can allocate memory internally which may trigger GC collection.
    // Conservative stack scanning requires GC roots to remain in stack slots;
    // willreturn would let LLVM optimize them into registers only, causing
    // the scanner to miss live objects (observed: map+filter loop at O2).
    annotate("ts_object_get_property",  false, false, true, false);
    annotate("ts_object_get_dynamic",   false, false, true, false);
    annotate("ts_object_set_property",  false, false, true, false);
    annotate("ts_object_set_dynamic",   false, false, true, false);
    annotate("ts_array_push",           false, false, true, false);
    annotate("ts_array_get",            false, false, true, false);
    annotate("ts_array_set",            false, false, true, false);
    annotate("ts_array_get_as_value",   false, false, true, false);
    annotate("ts_map_create",           false, false, true, false);
    annotate("ts_string_concat",        false, false, true, false);
    annotate("ts_string_from_value",    false, false, true, false);
    annotate("ts_alloc",                false, false, true, false);

    // --- Control flow: noreturn ---
    annotate("ts_throw",                false, false, true, false, /*noreturn=*/true);

    // NEVER annotate: ts_gc_write_barrier, ts_gc_safepoint, ts_gc_mark_object
}

void CodeGenerator::runOptimizations(const std::string& optLevel) {
    // Step 0: Annotate runtime function declarations with semantic attributes
    annotateRuntimeFunctions(*module);

    llvm::LoopAnalysisManager LAM;
    llvm::FunctionAnalysisManager FAM;
    llvm::CGSCCAnalysisManager CGAM;
    llvm::ModuleAnalysisManager MAM;

    llvm::PassBuilder PB(targetMachine.get());

    // Extension point: propagate known function pointers through closure dispatch
    PB.registerPipelineStartEPCallback(
        [](llvm::ModulePassManager& MPM, llvm::OptimizationLevel Level) {
            if (Level == llvm::OptimizationLevel::O0) return;
            MPM.addPass(llvm::CalledValuePropagationPass());
        });

    // Extension point: after each inlining round, catch box/unbox patterns
    PB.registerPeepholeEPCallback(
        [](llvm::FunctionPassManager& FPM, llvm::OptimizationLevel Level) {
            if (Level == llvm::OptimizationLevel::O0) return;
            FPM.addPass(llvm::InstCombinePass());
            FPM.addPass(llvm::EarlyCSEPass(/*UseMemorySSA=*/true));
        });

    // Extension point: eliminate redundant type guards before vectorizer
    PB.registerVectorizerStartEPCallback(
        [](llvm::FunctionPassManager& FPM, llvm::OptimizationLevel Level) {
            if (Level == llvm::OptimizationLevel::O0) return;
            FPM.addPass(llvm::ConstraintEliminationPass());
        });

    PB.registerModuleAnalyses(MAM);
    PB.registerCGSCCAnalyses(CGAM);
    PB.registerFunctionAnalyses(FAM);
    PB.registerLoopAnalyses(LAM);
    PB.crossRegisterProxies(LAM, FAM, CGAM, MAM);

    llvm::OptimizationLevel level;
    if (optLevel == "0") level = llvm::OptimizationLevel::O0;
    else if (optLevel == "1") level = llvm::OptimizationLevel::O1;
    else if (optLevel == "2") level = llvm::OptimizationLevel::O2;
    else if (optLevel == "3") level = llvm::OptimizationLevel::O3;
    else if (optLevel == "s") level = llvm::OptimizationLevel::Os;
    else if (optLevel == "z") level = llvm::OptimizationLevel::Oz;
    else level = llvm::OptimizationLevel::O0;

    // Compile-time guard: the O1+ pass pipeline contains a superlinear pass that
    // chokes on very large modules. Measured on the test262 `testIntl.js` harness
    // (~3k lines): O2 and O1 both ~24s, while O0 is ~1s — i.e. ~all the time is the
    // optimizer, not RS4GC/codegen. For such outliers force O0: optimization
    // quality is irrelevant for these huge generated/harness modules and
    // correctness is unaffected. Normal programs (well under the thresholds) keep
    // their requested level.
    if (level != llvm::OptimizationLevel::O0) {
        size_t totalInsts = 0, maxFuncInsts = 0;
        for (auto& F : *module) {
            if (F.isDeclaration()) continue;
            size_t fi = F.getInstructionCount();
            totalInsts += fi;
            if (fi > maxFuncInsts) maxFuncInsts = fi;
        }
        if (totalInsts > 200000 || maxFuncInsts > 10000) {
            SPDLOG_WARN("Module too large for O{} (total {} insts, max fn {} insts); "
                        "forcing O0 to avoid pathological optimizer compile time",
                        optLevel, totalInsts, maxFuncInsts);
            level = llvm::OptimizationLevel::O0;
        } else {
            SPDLOG_INFO("Module size: total {} insts, max fn {} insts (keeping O{})",
                        totalInsts, maxFuncInsts, optLevel);
        }
    }

    if (level != llvm::OptimizationLevel::O0) {
        SPDLOG_INFO("Running IR optimizations (Level O{})", optLevel);

        // Use buildPerModuleDefaultPipeline as the core. It includes:
        // SROA, EarlyCSE, InstCombine, SimplifyCFG, GVN, LICM,
        // LoopUnroll, CGSCC Inliner, GlobalOpt, IPSCCP, etc.
        // Our extension point callbacks inject ts-aot-specific passes.
        llvm::ModulePassManager MPM =
            PB.buildPerModuleDefaultPipeline(level);

        // Post-pipeline cleanup
        MPM.addPass(llvm::DeadArgumentEliminationPass());
        MPM.addPass(llvm::GlobalDCEPass());

        MPM.run(*module, MAM);
    }

    // Run RewriteStatepointsForGC pass when GC statepoints are enabled.
    // This must run AFTER standard optimizations but BEFORE code emission.
    // RS4GC rewrites calls with "deopt" bundles into gc.statepoint + gc.relocate
    // and generates the .llvm_stackmaps section for precise stack scanning.
    if (enableGCStatepoints_) {
        // (GC boundary normalization already ran at the top of emitObjectFile,
        // before the pre-optimization verify.)

        // Canonicalize call arg integer widths to each callee's declared
        // signature (e.g. ts_value_make_bool emitted as i1/i32/i64 at different
        // sites). RS4GC rejects width-mismatched calls that opaque pointers
        // otherwise tolerate; run this before RS4GC sees them.
        canonicalizeIntCallArgs(*module);

        // Add empty "deopt"() bundles to all calls in gc-attributed functions.
        // RS4GC requires these to generate operand-bundle-based statepoints
        // with correct gc.relocate indices.
        addDeoptBundles(*module);

        SPDLOG_INFO("Running RewriteStatepointsForGC pass");
        llvm::ModulePassManager GCMPM;
        GCMPM.addPass(llvm::RewriteStatepointsForGC());
        GCMPM.run(*module, MAM);

        // Fix gc.relocate indices: LLVM 18.1 RS4GC generates off-by-one indices
        // (counts statepoint result as gc-live[0]). Fix them to 0-based gc-live
        // bundle indexing that the verifier and backend expect.
        fixupGCRelocateIndices(*module);

        // Verify the module after RS4GC + fixup
        std::string errorStr;
        llvm::raw_string_ostream os(errorStr);
        if (llvm::verifyModule(*module, &os)) {
            SPDLOG_WARN("Module verification after RS4GC: {}", errorStr);
        } else {
            SPDLOG_INFO("Module verification passed after RS4GC");
        }
    }

    // Lower instrprof intrinsics into counter globals + profile data sections
    if (emitCoverage_) {
        llvm::ModulePassManager CovMPM;
        CovMPM.addPass(llvm::InstrProfilingLoweringPass());
        CovMPM.run(*module, MAM);

        // Fix counter linkage: InstrProfilingLoweringPass creates __profc_*
        // as linkonce_odr with COMDAT. On Windows/COFF, lld-link may discard
        // COMDAT copies, causing some counters to point at dead memory.
        // Change to internal linkage to ensure a single live copy per counter.
        for (auto& gv : module->globals()) {
            if (gv.getName().starts_with("__profc_") ||
                gv.getName().starts_with("__profd_") ||
                gv.getName().starts_with("__profn_")) {
                if (gv.hasComdat()) gv.setComdat(nullptr);
                if (gv.getLinkage() == llvm::GlobalValue::LinkOnceODRLinkage)
                    gv.setLinkage(llvm::GlobalValue::InternalLinkage);
            }
        }
    }
}

bool CodeGenerator::emitObjectFile(const std::string& filename, const std::string& optLevel) {
    // GC-001 step 2: normalize the runtime-call boundary to addrspace(0) BEFORE the
    // pre-optimization verify below — step 1 left external decls with addrspace(1)
    // pointer params (which mismatch addrspace(0) string-literal globals), so the
    // module is not yet valid until this runs.
    if (enableGCStatepoints_) {
        normalizeRuntimeBoundaryAddrSpaces(*module);
        // Canonicalize integer-width-mismatched call args (e.g. ts_value_make_bool
        // emitted i1/i32/i64 at different sites) to the callee's declared signature
        // BEFORE the pre-opt verify — opaque pointers tolerate the mismatch but the
        // verifier (and later RS4GC) do not.
        canonicalizeIntCallArgs(*module);
    }

    std::string errorStr;
    llvm::raw_string_ostream os(errorStr);
    if (llvm::verifyModule(*module, &os)) {
        // Check if the only errors are debug info related (!dbg subprogram)
        if (errorStr.find("!dbg") != std::string::npos &&
            errorStr.find("Call parameter type") == std::string::npos &&
            errorStr.find("PHINode") == std::string::npos) {
            SPDLOG_WARN("LLVM debug info verification warning (proceeding): {}", errorStr.substr(0, 200));
        } else {
            SPDLOG_ERROR("LLVM Module verification failed: {}", errorStr);
            return false;
        }
    }

    if (!setupTargetMachine(optLevel)) {
        return false;
    }

    runOptimizations(optLevel);

    std::error_code ec;
    llvm::raw_fd_ostream dest(filename, ec, llvm::sys::fs::OF_None);

    if (ec) {
        SPDLOG_ERROR("Could not open file {}: {}", filename, ec.message());
        return false;
    }

    llvm::legacy::PassManager pass;
    auto fileType = llvm::CodeGenFileType::ObjectFile;

    if (targetMachine->addPassesToEmitFile(pass, dest, nullptr, fileType)) {
        SPDLOG_ERROR("TargetMachine can't emit a file of this type");
        return false;
    }

    // Opt-in only (TSAOT_DEBUG_IR=1): this used to run UNCONDITIONALLY,
    // writing the full module IR to debug_ir.ll in the CWD on every
    // compile — a test262 sweep is ~40k compiles at -j24, i.e. tens of GB
    // of needless SSD writes per sweep plus 24 processes racing one file.
    if (const char* dbgIr = std::getenv("TSAOT_DEBUG_IR"); dbgIr && dbgIr[0] == '1') {
        SPDLOG_INFO("Dumping debug IR to debug_ir.ll");
        std::error_code ec2;
        llvm::raw_fd_ostream debugFile("debug_ir.ll", ec2, llvm::sys::fs::OF_None);
        module->print(debugFile, nullptr);
        debugFile.flush();
    }

    SPDLOG_INFO("Starting CodeGen passes");
    pass.run(*module);
    SPDLOG_INFO("Finished CodeGen passes");
    dest.flush();

    return true;
}

bool CodeGenerator::emitBitcode(const std::string& filename) {
    std::error_code ec;
    llvm::raw_fd_ostream dest(filename, ec, llvm::sys::fs::OF_None);
    if (ec) {
        SPDLOG_ERROR("Could not open file {}: {}", filename, ec.message());
        return false;
    }
    llvm::WriteBitcodeToFile(*module, dest);
    return true;
}

bool CodeGenerator::emitAssembly(const std::string& filename) {
    std::error_code ec;
    llvm::raw_fd_ostream dest(filename, ec, llvm::sys::fs::OF_None);
    if (ec) {
        SPDLOG_ERROR("Could not open file {}: {}", filename, ec.message());
        return false;
    }
    module->print(dest, nullptr);
    return true;
}

} // namespace ts
