const arr: Set<number>[] = [];
const s1 = new Set<number>();
s1.add(1);
s1.add(2);
console.log("s1.size before push:", s1.size);
arr.push(s1);
console.log("arr.length after push:", arr.length);
const s2 = arr[0];
console.log("typeof s2:", typeof s2);
console.log("s2:", s2);
console.log("s2.size:", s2.size);
