#!/usr/bin/env python3
"""
Stack Map Dump Tool for ts-aot GC Statepoints

Parses the .llvm_stackmaps section from COFF object files (.obj) or PE
executables (.exe) and prints a summary of GC safepoint information.

Usage:
    python tools/stackmap-dump.py <file.obj|file.exe>

The .llvm_stackmaps section is generated by LLVM's RewriteStatepointsForGC pass
when functions have the gc "ts-aot-gc" attribute. It records:
  - Which functions contain GC safepoints
  - The location of each safepoint (call site)
  - Which GC-managed pointers are live at each safepoint
  - Where those pointers are stored (register or stack offset)

Format reference: https://llvm.org/docs/StackMaps.html#stack-map-format
"""

import struct
import sys
import os


def read_coff_sections(data):
    """Parse COFF headers and return a dict of section_name -> (offset, size)."""
    if len(data) < 20:
        return {}

    machine, num_sections, _, sym_offset, num_symbols, opt_header_size, characteristics = \
        struct.unpack_from('<HHIIIHH', data, 0)

    sections = {}
    offset = 20 + opt_header_size
    str_table_offset = sym_offset + num_symbols * 18

    for i in range(num_sections):
        if offset + 40 > len(data):
            break

        name_bytes = data[offset:offset + 8]
        if name_bytes[0:1] == b'/' and name_bytes[1:2] != b'\x00':
            # Long name - index into string table
            try:
                idx = int(name_bytes[1:].rstrip(b'\x00'))
                end = data.index(b'\x00', str_table_offset + idx)
                name = data[str_table_offset + idx:end].decode('ascii', errors='replace')
            except (ValueError, IndexError):
                name = name_bytes.rstrip(b'\x00').decode('ascii', errors='replace')
        else:
            name = name_bytes.rstrip(b'\x00').decode('ascii', errors='replace')

        vsize, vaddr, raw_size, raw_ptr = struct.unpack_from('<IIII', data, offset + 8)
        sections[name] = (raw_ptr, raw_size)
        offset += 40

    return sections


def read_pe_sections(data):
    """Parse PE headers and return a dict of section_name -> (offset, size)."""
    if len(data) < 64:
        return {}

    # Check MZ signature
    if data[0:2] != b'MZ':
        return {}

    # Get PE header offset from MZ header
    pe_offset = struct.unpack_from('<I', data, 60)[0]
    if pe_offset + 4 > len(data) or data[pe_offset:pe_offset + 4] != b'PE\x00\x00':
        return {}

    # COFF header starts at pe_offset + 4
    coff_offset = pe_offset + 4
    machine, num_sections, _, sym_offset, num_symbols, opt_header_size, characteristics = \
        struct.unpack_from('<HHIIIHH', data, coff_offset)

    sections = {}
    section_offset = coff_offset + 20 + opt_header_size

    for i in range(num_sections):
        if section_offset + 40 > len(data):
            break

        name_bytes = data[section_offset:section_offset + 8]
        name = name_bytes.rstrip(b'\x00').decode('ascii', errors='replace')

        vsize, vaddr, raw_size, raw_ptr = struct.unpack_from('<IIII', data, section_offset + 8)
        sections[name] = (raw_ptr, raw_size)
        section_offset += 40

    return sections


def parse_stackmap(data, offset, size):
    """Parse LLVM stack map format (version 3).

    Format:
      Header (16 bytes):
        uint8  version
        uint8  reserved0
        uint16 reserved1
        uint32 num_functions
        uint32 num_constants
        uint32 num_records

      Function entries (24 bytes each):
        uint64 function_address
        uint64 stack_size
        uint64 record_count

      Constants (8 bytes each):
        uint64 value

      Records (variable size):
        uint64 patchpoint_id
        uint32 instruction_offset
        uint16 reserved
        uint16 num_locations
        Location entries (12 bytes each):
          uint8  type  (1=Register, 2=Direct, 3=Indirect, 4=Constant, 5=ConstantIndex)
          uint8  reserved
          uint16 dwarf_regnum
          int32  offset_or_value
          -- padding to 12 bytes --
        uint16 padding (alignment)
        uint16 num_live_outs
        LiveOut entries (4 bytes each):
          uint16 dwarf_regnum
          uint8  reserved
          uint8  size_in_bytes
        -- padding to 8-byte alignment --
    """
    end = offset + size
    if size < 16:
        print("  Stack map section too small for header")
        return

    version, res0, res1, num_functions, num_constants, num_records = \
        struct.unpack_from('<BBHIII', data, offset)

    print(f"\n  Stack Map Header:")
    print(f"    Version:      {version}")
    print(f"    Functions:    {num_functions}")
    print(f"    Constants:    {num_constants}")
    print(f"    Records:      {num_records}")

    pos = offset + 16

    # Parse function entries
    functions = []
    print(f"\n  Functions:")
    for i in range(num_functions):
        if pos + 24 > end:
            print(f"    [truncated at function {i}]")
            break
        func_addr, stack_size, record_count = struct.unpack_from('<QQQ', data, pos)
        functions.append((func_addr, stack_size, record_count))
        print(f"    [{i}] addr=0x{func_addr:016X}  stack_size={stack_size}  records={record_count}")
        pos += 24

    # Parse constants
    if num_constants > 0:
        print(f"\n  Constants:")
        for i in range(num_constants):
            if pos + 8 > end:
                break
            val = struct.unpack_from('<Q', data, pos)[0]
            print(f"    [{i}] 0x{val:016X} ({val})")
            pos += 8

    # Parse records
    location_type_names = {
        1: "Register",
        2: "Direct",
        3: "Indirect",
        4: "Constant",
        5: "ConstIndex",
    }

    # Map records to functions
    func_idx = 0
    records_remaining = functions[0][2] if functions else 0

    print(f"\n  Records:")
    total_gc_ptrs = 0
    for i in range(num_records):
        if pos + 8 > end:
            print(f"    [truncated at record {i}]")
            break

        # Track which function this record belongs to
        while func_idx < len(functions) - 1 and records_remaining == 0:
            func_idx += 1
            records_remaining = functions[func_idx][2]

        patchpoint_id = struct.unpack_from('<Q', data, pos)[0]
        pos += 8

        if pos + 4 > end:
            break
        instr_offset = struct.unpack_from('<I', data, pos)[0]
        pos += 4

        if pos + 4 > end:
            break
        reserved, num_locations = struct.unpack_from('<HH', data, pos)
        pos += 4

        print(f"    [{i}] func={func_idx}  id=0x{patchpoint_id:X}  "
              f"instr_offset=0x{instr_offset:X}  locations={num_locations}")

        gc_ptr_count = 0
        for j in range(num_locations):
            if pos + 12 > end:
                break
            # V3 location entry: 12 bytes
            #   uint8  type
            #   uint8  reserved
            #   uint16 size
            #   uint16 dwarf_regnum
            #   uint16 reserved
            #   int32  offset
            loc_type, loc_res, loc_size, dwarf_reg, loc_res2, loc_offset = \
                struct.unpack_from('<BBHHHi', data, pos)
            pos += 12

            type_name = location_type_names.get(loc_type, f"Unknown({loc_type})")
            if loc_type == 3:  # Indirect = stack slot (potential GC pointer)
                gc_ptr_count += 1
                print(f"      loc[{j}] {type_name}  reg={dwarf_reg}  "
                      f"offset={loc_offset}  size={loc_size}  [GC ptr on stack]")
            elif loc_type == 1:  # Register
                gc_ptr_count += 1
                print(f"      loc[{j}] {type_name}  reg={dwarf_reg}  "
                      f"size={loc_size}  [GC ptr in register]")

        total_gc_ptrs += gc_ptr_count

        # Align to 8 bytes after locations
        if pos % 8 != 0:
            pos += 8 - (pos % 8)

        # Live outs header: uint16 padding + uint16 num_live_outs
        if pos + 4 > end:
            break
        pad, num_live_outs = struct.unpack_from('<HH', data, pos)
        pos += 4

        for j in range(num_live_outs):
            if pos + 4 > end:
                break
            pos += 4

        # Align to 8-byte boundary after live outs
        if pos % 8 != 0:
            pos += 8 - (pos % 8)

        records_remaining -= 1

    print(f"\n  Summary:")
    print(f"    Total functions with statepoints: {num_functions}")
    print(f"    Total safepoints (records):       {num_records}")
    print(f"    Total GC pointer locations:       {total_gc_ptrs}")


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file.obj|file.exe>")
        print()
        print("Dump LLVM stack map information from a compiled ts-aot binary.")
        print("The binary must be compiled with --gc-statepoints to contain stack maps.")
        sys.exit(1)

    filepath = sys.argv[1]
    if not os.path.exists(filepath):
        print(f"Error: File not found: {filepath}")
        sys.exit(1)

    with open(filepath, 'rb') as f:
        data = f.read()

    print(f"File: {filepath}")
    print(f"Size: {len(data)} bytes")

    # Try PE first, then COFF
    sections = {}
    file_type = "unknown"

    if data[0:2] == b'MZ':
        sections = read_pe_sections(data)
        file_type = "PE executable"
    else:
        sections = read_coff_sections(data)
        file_type = "COFF object"

    print(f"Type: {file_type}")
    print(f"Sections: {len(sections)}")

    # Look for .llvm_stackmaps
    stackmap_section = None
    for name, (offset, size) in sections.items():
        if 'stackmap' in name.lower() or 'llvm_st' in name.lower():
            stackmap_section = (name, offset, size)
            break

    if stackmap_section:
        name, offset, size = stackmap_section
        print(f"\nFound stack map section: '{name}' at offset 0x{offset:X}, size {size} bytes")
        parse_stackmap(data, offset, size)
    else:
        print("\nNo .llvm_stackmaps section found.")
        print("This is expected when:")
        print("  - The file was NOT compiled with --gc-statepoints")
        print("  - All pointers are in addrspace(0) (no GC-managed pointers yet)")
        print("  - RS4GC found no live GC pointers to track")
        print()
        print("Available sections:")
        for name, (offset, size) in sorted(sections.items()):
            print(f"  {name:30s}  offset=0x{offset:08X}  size={size}")


if __name__ == '__main__':
    main()
